### PR TITLE
fix: ratelimit may lose precision on Linux

### LINKED ISSUE #509: Linux机器部署, 当rateLimite限速大于1万时, 实际的限速就不和配置的限速同步变化了
1. 问题描述:     
    linxu机器部署, 假如日志数据生成的QPS时3万, 当rateLimite限速为3000时, 实际的最高速度也是3000, 当限制10000实际最高也是10000. 但是, 当配置rateLimite限速到2万时, 实际限制到1万3千左右, rateLimite配置到10万时候, 实际限速2万左右. 
    不过, 在mac机器下运行就没有这个问题.

2. loggie版本: 主分支、1.3、1.4都有这个问题

3. 问题复现配置: 
pipeline yml:

pipelines:
  - name: local
    sources:
      - type: dev
        name: demo
        eventsTotal: -1
        byteSize: 1024
        qps: 30000
    interceptors:
      - type: rateLimit
        qps: 20000
    sink:
      type: dev
      codec:
        type: json
        printEvents: false
        pretty: true

### PR DESCRIPTION
**Pull request by mmaxiaolei**
#### Proposed Changes:

* ratelimit interceptor

#### Which issue(s) this PR fixes:

Fixes #509

#### Additional documentation:

```docs

highPrecision: true

> The high precision mode of the rate limiting component can be enabled, but it comes with the cost of increased CPU usage. Consider enabling it when the limited QPS exceeds 20,000

```

### CODE REVIEW

File: pkg/interceptor/limit/clock.go [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+type clockDescriptor struct {
+	clock Clock
+}
+
+func NewHighPrecisionClockDescriptor(clock Clock) Clock {
+	return &clockDescriptor{clock: clock}
+}
+
+func (c *clockDescriptor) Sleep(d time.Duration) {
+	// 小于10ms的睡眠使用长轮询来代替以提高精度
```
Comment (ethfoo) [inline pkg/interceptor/limit/clock.go:30]: 英文
